---
# Instance Parameters
OS:
# for CentOS7
  - Name: "CentOS Linux 7 x86_64*"
    Region: ap-northeast-1
    Owners: aws-marketplace
#  - Name: "Windows_Server-2016-Japanese-Full-Base-*"
#    Region: ap-northeast-1
#    Owners: amazon

Instance:
   - Name: testec2instance01a
     ENI: 
       Create: true
       ENIDeviceIndex:
         - 1
     Tagname: test-ec2instance01a
     AvailabilityZone: ap-northeast-1a
     EbsOptimized: true
     ImageId:
     IamInstanceProfile: testinstanceprofile01
     InstanceInitiatedShutdownBehavior: stop
     InstanceType: t3.micro
     KeyName: testkeypair
     Monitoring: false
     PlacementGroupName:
     SecurityGroups:
       - test-sg01
     SourceDestCheck: false
     NetworkInterfaces:
       - AssociatePublicIpAddress: false
         DeleteOnTermination: false
         Description: 'test eni01'
         DeviceIndex: 0
         PrivateIpAddress: 192.168.0.11
         SubnetName: test-subnet1a
       - AssociatePublicIpAddress: false
         DeleteOnTermination: false
         Description: 'test eni02'
         DeviceIndex: 1
         PrivateIpAddress: 192.168.11.11
         SubnetName: test-subnet1c
     BlockDeviceMappings:
       - DeviceName: /dev/xvda
         Ebs:
           DeleteOnTermination: true
           Encrypted: false
           Iops: 
           VolumeSize: 30
           VolumeType: gp2
         
