---
# tasks file for 02-create-template-natgateway
- name: VPC parameter get
  ec2_vpc_net_facts:
    region: "{{ VPC.Region }}"
    filters:
      "tag:Name": "{{ VPC.Tagname }}"
  register: vpc_net_facts

- name: Get EIP facts
  ec2_eip_facts:
    region: "{{ VPC.Region }}"
  register: eip_facts

- name: Get subnet facts
  ec2_vpc_subnet_facts:
    region: "{{ VPC.Region }}"
    filters:
      vpc-id: "{{ vpc_net_facts.vpcs[0].vpc_id }}"
  register: vpc_subnet_facts

- name: create template file for NAT Gateway
  template:
    src: 02-create_natgateway.yml
    dest: /tmp/02-create_natgateway.yml
  failed_when:
    - vpc_net_facts.vpcs[0].vpc_id.find('vpc-') == -1
    - eip_facts.addresses[0].allocation_id.find('eipalloc-') == -1
    - vpc_subnet_facts.subnets[0].subnet_id.find('subnet-') == -1
