---
# tasks file for 04-create-template-networkacl
- name: VPC parameter get
  ec2_vpc_net_facts:
    region: "{{ VPC.Region }}"
    filters:
      "tag:Name": "{{ VPC.Tagname }}"
  register: vpc_net_facts

- name: create template file for Network ACL
  template:
    src: 04-create_networkacl.yml
    dest: /tmp/04-create_networkacl.yml
  failed_when:
    - vpc_net_facts.vpcs[0].vpc_id.find('vpc-') == -1
